# code: language=ansible
---
- name: Copy over the timesyncd config
  ansible.builtin.template:
    src: timesyncd.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart timesyncd Service
