# code: language=ansible
---
- name: Restart timesyncd Service
  become: true
  ansible.builtin.service:
    name: systemd-timesyncd.service
    state: restarted

- name: Restart Chrony Service
  become: true
  ansible.builtin.service:
    name: chronyd.service
    state: restarted
