# code: language=ansible
---
armbian:
  hosts:
    lepotato-node-0.barneycompound.com:
    lepotato-node-1.barneycompound.com:

ubuntu:
  hosts:
    ubuntu-docker-host-1.barneycompound.com:
    ubuntu-docker-host-2.barneycompound.com:
    ubuntu-docker-host-3.barneycompound.com:

git_nodes:
  children:
    armbian:
    ubuntu:

k3s_master:
  hosts:
    k3s-server-00.barneycompound.com:
    k3s-server-01.barneycompound.com:
    k3s-server-02.barneycompound.com:

k3s_nodes:
  hosts:
    k3s-node-00.barneycompound.com:
    k3s-node-01.barneycompound.com:
    k3s-node-02.barneycompound.com:

k3s_cluster:
  children:
    k3s_master:
    k3s_nodes:
