# code: language=ansible
---
- name: Add Global Git config files to new hosts
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'
  loop:
    - src: gitconfig/.gitconfig
      dest: /home/{{ user }}/.gitconfig
    - src: gitconfig/alias.gitconfig
      dest: /home/{{ user }}/.alias.gitconfig
    - src: gitconfig/colors.gitconfig
      dest: /home/{{ user }}/.colors.gitconfig
  when: setup_git_client
